# 기출문제 6회(2023.06.24)

## 1유형

In [1]:
import numpy as np
import pandas as pd

c:\Users\kjh\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\kjh\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_1.csv')
df

     구급대                 출동시간                 도착시간
0   구급대8  2020-07-10 06:11:45  2020-07-10 06:52:06
1   구급대9  2020-07-13 06:12:21  2020-07-13 07:58:59
2   구급대1  2020-07-06 06:12:29  2020-07-06 07:51:55
3   구급대5  2020-07-21 06:11:41  2020-07-21 08:08:36
4   구급대1  2020-07-29 06:12:00  2020-07-29 07:24:21
..   ...                  ...                  ...
95  구급대3  2020-07-06 06:12:27  2020-07-06 06:50:09
96  구급대6  2020-07-17 06:12:02  2020-07-17 06:16:49
97  구급대7  2020-07-12 06:12:22  2020-07-12 07:32:26
98  구급대6  2020-07-08 06:12:05  2020-07-08 06:41:31
99  구급대8  2020-07-10 06:12:16  2020-07-10 06:30:46

[100 rows x 3 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구급대     100 non-null    object
 1   출동시간    100 non-null    object
 2   도착시간    100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

In [6]:
df['출동시간'] = pd.to_datetime(df['출동시간'])
df['도착시간'] = pd.to_datetime(df['도착시간'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구급대     100 non-null    object
 1   출동시간    100 non-null    datetime64[ns]
 2   도착시간    100 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(1)
memory usage: 2.5+ KB

In [8]:
df['이동시간'] = df['도착시간'] - df['출동시간']
df

     구급대                출동시간                도착시간            이동시간
0   구급대8 2020-07-10 06:11:45 2020-07-10 06:52:06 0 days 00:40:21
1   구급대9 2020-07-13 06:12:21 2020-07-13 07:58:59 0 days 01:46:38
2   구급대1 2020-07-06 06:12:29 2020-07-06 07:51:55 0 days 01:39:26
3   구급대5 2020-07-21 06:11:41 2020-07-21 08:08:36 0 days 01:56:55
4   구급대1 2020-07-29 06:12:00 2020-07-29 07:24:21 0 days 01:12:21
..   ...                 ...                 ...             ...
95  구급대3 2020-07-06 06:12:27 2020-07-06 06:50:09 0 days 00:37:42
96  구급대6 2020-07-17 06:12:02 2020-07-17 06:16:49 0 days 00:04:47
97  구급대7 2020-07-12 06:12:22 2020-07-12 07:32:26 0 days 01:20:04
98  구급대6 2020-07-08 06:12:05 2020-07-08 06:41:31 0 days 00:29:26
99  구급대8 2020-07-10 06:12:16 2020-07-10 06:30:46 0 days 00:18:30

[100 rows x 4 columns]

In [9]:
df['이동시간'] = df['이동시간'].dt.total_seconds() / 60

In [10]:
df

     구급대                출동시간                도착시간        이동시간
0   구급대8 2020-07-10 06:11:45 2020-07-10 06:52:06   40.350000
1   구급대9 2020-07-13 06:12:21 2020-07-13 07:58:59  106.633333
2   구급대1 2020-07-06 06:12:29 2020-07-06 07:51:55   99.433333
3   구급대5 2020-07-21 06:11:41 2020-07-21 08:08:36  116.916667
4   구급대1 2020-07-29 06:12:00 2020-07-29 07:24:21   72.350000
..   ...                 ...                 ...         ...
95  구급대3 2020-07-06 06:12:27 2020-07-06 06:50:09   37.700000
96  구급대6 2020-07-17 06:12:02 2020-07-17 06:16:49    4.783333
97  구급대7 2020-07-12 06:12:22 2020-07-12 07:32:26   80.066667
98  구급대6 2020-07-08 06:12:05 2020-07-08 06:41:31   29.433333
99  구급대8 2020-07-10 06:12:16 2020-07-10 06:30:46   18.500000

[100 rows x 4 columns]

In [12]:
# 구급대별 평균 이동시간
print(df.groupby('구급대')['이동시간'].mean())

구급대
구급대1     54.952381
구급대10    42.365000
구급대2     60.228571
구급대3     43.490741
구급대4     49.136667
구급대5     61.250000
구급대6     41.764583
구급대7     83.337037
구급대8     42.693750
구급대9     80.658889
Name: 이동시간, dtype: float64

In [17]:
print(round(max(df.groupby('구급대')['이동시간'].mean())))

83

In [31]:
# 2
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_2.csv')
df

     대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과
0    대학교1  20   121    72     158    131    77    59
1    대학교2  31   178   139     145    137    63    90
2    대학교3  23   136   139     154    111    91    50
3    대학교4  32    72   136      67     51   133   159
4    대학교5  22    61    73      86     82    55   124
5    대학교6  32   169   172     137    173    59   128
6    대학교7  29   173   183     112    154   134   133
7    대학교8  19   141    81     101    118   151   123
8    대학교9  40   137   145     191     58    96    71
9   대학교10  34   197    93     125    116   181   150
10  대학교11  21   136   139     136    126    54    98
11  대학교12  37    72   113      53    180   118   153
12  대학교13  36   138    65     153    126   139   189
13  대학교14  34    95    89     179    164   131   167
14  대학교15  20    52    84     160     99    55   113
15  대학교16  30   129   191     117     50    77    66
16  대학교17  35   143    72      71    161    52   177
17  대학교18  31    68   187     113     57   133   113
18  대학교19  34    58   140     141    126   149    56
19  대학교20  39    91   131      66     86   146   101
20  대학교21  31    50   156     103    111    51   156
21  대학교22  26   166   178     197    120   136    62
22  대학교23  39    83   156      58    124   139   133
23  대학교24  23    71    94     178    121   157    93
24  대학교25  24    81    55     159    177    83   172
25  대학교26  19    89   127     135    112   124   121
26  대학교27  31   128    66      56     81   195   150
27  대학교28  36    60   170     188     86   133   144
28  대학교29  21    78   113     123    110    82   192
29  대학교30  27   195    63     189     98   129   129
30  대학교31  26    58   168     179    123   198    53
31  대학교32  40   152   138     108     65    64   190
32  대학교33  38   190   136      55     87   128   122
33  대학교34  29   148   108      66    114   122    93
34  대학교35  32   137    86      72     52   124   133
35  대학교36  25   159   104     177     61   158    66
36  대학교37  32   141   158      61     53   177    92
37  대학교38  40    60   141     162    102   111   110
38  대학교39  23    93    62     190    106    66   159
39  대학교40  25    61   121     184     92   185    99
40  대학교41  20    64    88      79    168    73    84
41  대학교42  37    98   152     195    161   186   143
42  대학교43  28   177   169     107    122   185    73
43  대학교44  22    87   106     167    160   101   153
44  대학교45  21   105    72     162     60   186   129
45  대학교46  22   163   189     192    121    99   183
46  대학교47  34    85    51      91     72   134    58
47  대학교48  41    57   103      59     89   184    75
48  대학교49  21   150   158     159     78    65   195
49  대학교50  42    71   102     148     96   157    82

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대학교명    50 non-null     object
 1   교수      50 non-null     int64
 2   경영학과    50 non-null     int64
 3   경제학과    50 non-null     int64
 4   컴퓨터공학과  50 non-null     int64
 5   산업공학과   50 non-null     int64
 6   국문학과    50 non-null     int64
 7   영문학과    50 non-null     int64
dtypes: int64(7), object(1)
memory usage: 3.2+ KB

In [33]:
df['총학생수'] = df['경영학과'] + df['경제학과'] + df['국문학과'] + df['산업공학과'] + df['영문학과'] + df['컴퓨터공학과']
df

     대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과  총학생수
0    대학교1  20   121    72     158    131    77    59   618
1    대학교2  31   178   139     145    137    63    90   752
2    대학교3  23   136   139     154    111    91    50   681
3    대학교4  32    72   136      67     51   133   159   618
4    대학교5  22    61    73      86     82    55   124   481
5    대학교6  32   169   172     137    173    59   128   838
6    대학교7  29   173   183     112    154   134   133   889
7    대학교8  19   141    81     101    118   151   123   715
8    대학교9  40   137   145     191     58    96    71   698
9   대학교10  34   197    93     125    116   181   150   862
10  대학교11  21   136   139     136    126    54    98   689
11  대학교12  37    72   113      53    180   118   153   689
12  대학교13  36   138    65     153    126   139   189   810
13  대학교14  34    95    89     179    164   131   167   825
14  대학교15  20    52    84     160     99    55   113   563
15  대학교16  30   129   191     117     50    77    66   630
16  대학교17  35   143    72      71    161    52   177   676
17  대학교18  31    68   187     113     57   133   113   671
18  대학교19  34    58   140     141    126   149    56   670
19  대학교20  39    91   131      66     86   146   101   621
20  대학교21  31    50   156     103    111    51   156   627
21  대학교22  26   166   178     197    120   136    62   859
22  대학교23  39    83   156      58    124   139   133   693
23  대학교24  23    71    94     178    121   157    93   714
24  대학교25  24    81    55     159    177    83   172   727
25  대학교26  19    89   127     135    112   124   121   708
26  대학교27  31   128    66      56     81   195   150   676
27  대학교28  36    60   170     188     86   133   144   781
28  대학교29  21    78   113     123    110    82   192   698
29  대학교30  27   195    63     189     98   129   129   803
30  대학교31  26    58   168     179    123   198    53   779
31  대학교32  40   152   138     108     65    64   190   717
32  대학교33  38   190   136      55     87   128   122   718
33  대학교34  29   148   108      66    114   122    93   651
34  대학교35  32   137    86      72     52   124   133   604
35  대학교36  25   159   104     177     61   158    66   725
36  대학교37  32   141   158      61     53   177    92   682
37  대학교38  40    60   141     162    102   111   110   686
38  대학교39  23    93    62     190    106    66   159   676
39  대학교40  25    61   121     184     92   185    99   742
40  대학교41  20    64    88      79    168    73    84   556
41  대학교42  37    98   152     195    161   186   143   935
42  대학교43  28   177   169     107    122   185    73   833
43  대학교44  22    87   106     167    160   101   153   774
44  대학교45  21   105    72     162     60   186   129   714
45  대학교46  22   163   189     192    121    99   183   947
46  대학교47  34    85    51      91     72   134    58   491
47  대학교48  41    57   103      59     89   184    75   567
48  대학교49  21   150   158     159     78    65   195   805
49  대학교50  42    71   102     148     96   157    82   656

In [34]:
df['인당학생수'] = round(df['총학생수'] / df['교수'])
df

     대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과  총학생수  인당학생수
0    대학교1  20   121    72     158    131    77    59   618   31.0
1    대학교2  31   178   139     145    137    63    90   752   24.0
2    대학교3  23   136   139     154    111    91    50   681   30.0
3    대학교4  32    72   136      67     51   133   159   618   19.0
4    대학교5  22    61    73      86     82    55   124   481   22.0
5    대학교6  32   169   172     137    173    59   128   838   26.0
6    대학교7  29   173   183     112    154   134   133   889   31.0
7    대학교8  19   141    81     101    118   151   123   715   38.0
8    대학교9  40   137   145     191     58    96    71   698   17.0
9   대학교10  34   197    93     125    116   181   150   862   25.0
10  대학교11  21   136   139     136    126    54    98   689   33.0
11  대학교12  37    72   113      53    180   118   153   689   19.0
12  대학교13  36   138    65     153    126   139   189   810   22.0
13  대학교14  34    95    89     179    164   131   167   825   24.0
14  대학교15  20    52    84     160     99    55   113   563   28.0
15  대학교16  30   129   191     117     50    77    66   630   21.0
16  대학교17  35   143    72      71    161    52   177   676   19.0
17  대학교18  31    68   187     113     57   133   113   671   22.0
18  대학교19  34    58   140     141    126   149    56   670   20.0
19  대학교20  39    91   131      66     86   146   101   621   16.0
20  대학교21  31    50   156     103    111    51   156   627   20.0
21  대학교22  26   166   178     197    120   136    62   859   33.0
22  대학교23  39    83   156      58    124   139   133   693   18.0
23  대학교24  23    71    94     178    121   157    93   714   31.0
24  대학교25  24    81    55     159    177    83   172   727   30.0
25  대학교26  19    89   127     135    112   124   121   708   37.0
26  대학교27  31   128    66      56     81   195   150   676   22.0
27  대학교28  36    60   170     188     86   133   144   781   22.0
28  대학교29  21    78   113     123    110    82   192   698   33.0
29  대학교30  27   195    63     189     98   129   129   803   30.0
30  대학교31  26    58   168     179    123   198    53   779   30.0
31  대학교32  40   152   138     108     65    64   190   717   18.0
32  대학교33  38   190   136      55     87   128   122   718   19.0
33  대학교34  29   148   108      66    114   122    93   651   22.0
34  대학교35  32   137    86      72     52   124   133   604   19.0
35  대학교36  25   159   104     177     61   158    66   725   29.0
36  대학교37  32   141   158      61     53   177    92   682   21.0
37  대학교38  40    60   141     162    102   111   110   686   17.0
38  대학교39  23    93    62     190    106    66   159   676   29.0
39  대학교40  25    61   121     184     92   185    99   742   30.0
40  대학교41  20    64    88      79    168    73    84   556   28.0
41  대학교42  37    98   152     195    161   186   143   935   25.0
42  대학교43  28   177   169     107    122   185    73   833   30.0
43  대학교44  22    87   106     167    160   101   153   774   35.0
44  대학교45  21   105    72     162     60   186   129   714   34.0
45  대학교46  22   163   189     192    121    99   183   947   43.0
46  대학교47  34    85    51      91     72   134    58   491   14.0
47  대학교48  41    57   103      59     89   184    75   567   14.0
48  대학교49  21   150   158     159     78    65   195   805   38.0
49  대학교50  42    71   102     148     96   157    82   656   16.0

In [35]:
# 22
a = df.sort_values(by = '인당학생수',ascending = False)
a

     대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과  총학생수  인당학생수
45  대학교46  22   163   189     192    121    99   183   947   43.0
48  대학교49  21   150   158     159     78    65   195   805   38.0
7    대학교8  19   141    81     101    118   151   123   715   38.0
25  대학교26  19    89   127     135    112   124   121   708   37.0
43  대학교44  22    87   106     167    160   101   153   774   35.0
44  대학교45  21   105    72     162     60   186   129   714   34.0
10  대학교11  21   136   139     136    126    54    98   689   33.0
28  대학교29  21    78   113     123    110    82   192   698   33.0
21  대학교22  26   166   178     197    120   136    62   859   33.0
23  대학교24  23    71    94     178    121   157    93   714   31.0
0    대학교1  20   121    72     158    131    77    59   618   31.0
6    대학교7  29   173   183     112    154   134   133   889   31.0
30  대학교31  26    58   168     179    123   198    53   779   30.0
2    대학교3  23   136   139     154    111    91    50   681   30.0
42  대학교43  28   177   169     107    122   185    73   833   30.0
29  대학교30  27   195    63     189     98   129   129   803   30.0
24  대학교25  24    81    55     159    177    83   172   727   30.0
39  대학교40  25    61   121     184     92   185    99   742   30.0
35  대학교36  25   159   104     177     61   158    66   725   29.0
38  대학교39  23    93    62     190    106    66   159   676   29.0
14  대학교15  20    52    84     160     99    55   113   563   28.0
40  대학교41  20    64    88      79    168    73    84   556   28.0
5    대학교6  32   169   172     137    173    59   128   838   26.0
9   대학교10  34   197    93     125    116   181   150   862   25.0
41  대학교42  37    98   152     195    161   186   143   935   25.0
1    대학교2  31   178   139     145    137    63    90   752   24.0
13  대학교14  34    95    89     179    164   131   167   825   24.0
33  대학교34  29   148   108      66    114   122    93   651   22.0
12  대학교13  36   138    65     153    126   139   189   810   22.0
17  대학교18  31    68   187     113     57   133   113   671   22.0
26  대학교27  31   128    66      56     81   195   150   676   22.0
4    대학교5  22    61    73      86     82    55   124   481   22.0
27  대학교28  36    60   170     188     86   133   144   781   22.0
15  대학교16  30   129   191     117     50    77    66   630   21.0
36  대학교37  32   141   158      61     53   177    92   682   21.0
18  대학교19  34    58   140     141    126   149    56   670   20.0
20  대학교21  31    50   156     103    111    51   156   627   20.0
3    대학교4  32    72   136      67     51   133   159   618   19.0
11  대학교12  37    72   113      53    180   118   153   689   19.0
34  대학교35  32   137    86      72     52   124   133   604   19.0
32  대학교33  38   190   136      55     87   128   122   718   19.0
16  대학교17  35   143    72      71    161    52   177   676   19.0
31  대학교32  40   152   138     108     65    64   190   717   18.0
22  대학교23  39    83   156      58    124   139   133   693   18.0
37  대학교38  40    60   141     162    102   111   110   686   17.0
8    대학교9  40   137   145     191     58    96    71   698   17.0
19  대학교20  39    91   131      66     86   146   101   621   16.0
49  대학교50  42    71   102     148     96   157    82   656   16.0
46  대학교47  34    85    51      91     72   134    58   491   14.0
47  대학교48  41    57   103      59     89   184    75   567   14.0

In [47]:
a.loc[45,'교수']

22

In [72]:
# 3
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_3.csv')
df

           날짜  폭력범죄  지능범죄  교통범죄  절도범죄  경제범죄  정치범죄 주요검찰청명
0   2018년 01월    28   127    90    73    33   202   검찰청1
1   2018년 02월    16   137    72    80    30   180   검찰청5
2   2018년 03월    29   140    70    79    34   211   검찰청5
3   2018년 04월    10   140    90    65    31   184   검찰청1
4   2018년 05월    11   138    70    75    35   190   검찰청1
5   2018년 06월    30   128    78    74    34   216   검찰청5
6   2018년 07월    21   128    84    69    31   181   검찰청1
7   2018년 08월    26   120    86    76    33   188   검찰청5
8   2018년 09월    11   117    86    65    33   192   검찰청5
9   2018년 10월    12   117    86    67    28   200   검찰청5
10  2018년 11월    22   103    83    72    33   196   검찰청1
11  2018년 12월    28   124    83    61    27   209   검찰청2
12  2019년 01월    22   102    86    62    28   212   검찰청1
13  2019년 02월    26   138    80    61    31   183   검찰청3
14  2019년 03월    14   129    76    60    29   202   검찰청5
15  2019년 04월    26   142    83    71    33   182   검찰청1
16  2019년 05월    28   131    80    72    28   212   검찰청1
17  2019년 06월    22   104    84    72    34   201   검찰청2
18  2019년 07월    14   134    84    72    32   182   검찰청2
19  2019년 08월    27   101    71    67    31   198   검찰청1
20  2019년 09월    21   108    87    70    33   187   검찰청1
21  2019년 10월    21   114    89    61    32   212   검찰청3
22  2019년 11월    22   134    79    64    35   198   검찰청4
23  2019년 12월    21   142    77    62    35   183   검찰청3
24  2020년 01월    23   140    83    60    26   219   검찰청2
25  2020년 02월    11   111    73    60    31   211   검찰청1
26  2020년 03월    17   125    87    76    25   220   검찰청5
27  2020년 04월    10   112    78    78    28   185   검찰청3
28  2020년 05월    20   122    76    74    30   192   검찰청1
29  2020년 06월    24   139    87    77    29   192   검찰청3
30  2020년 07월    19   107    79    80    30   193   검찰청3
31  2020년 08월    27   124    81    62    29   187   검찰청5
32  2020년 09월    25   108    76    66    28   182   검찰청1
33  2020년 10월    25   134    71    75    33   189   검찰청5
34  2020년 11월    26   122    72    62    31   180   검찰청3
35  2020년 12월    22   104    87    80    31   181   검찰청5
36  2021년 01월    28   102    90    73    33   212   검찰청3
37  2021년 02월    16   173    72    80    50   150   검찰청2
38  2021년 03월    39   120    70    69    34   231   검찰청1
39  2021년 04월    26   122    83    71    33   192   검찰청4
40  2021년 05월    28   111    80    72    28   182   검찰청2
41  2021년 06월   122    94    84    92    34   211   검찰청2
42  2021년 07월    19   117    79    70    30   151   검찰청3
43  2021년 08월    27   131    81    62    29   189   검찰청5
44  2021년 09월    25   113    76    66    38   172   검찰청1
45  2021년 10월    20   115    80    77    33   138   검찰청3
46  2021년 11월    25   149    90    67    33   191   검찰청2
47  2021년 12월    21   116    87    72    38   206   검찰청4
48  2022년 01월    16   104    82    60    25   206   검찰청5
49  2022년 02월    19   145    88    60    30   204   검찰청1
50  2022년 03월    17   144    84    76    34   197   검찰청5
51  2022년 04월    14   150    85    75    31   181   검찰청5
52  2022년 05월    22   119    73    74    34   200   검찰청1
53  2022년 06월    12   131    78    65    30   201   검찰청3
54  2022년 07월    12   116    79    65    31   202   검찰청4
55  2022년 08월    25   129    77    69    33   185   검찰청2
56  2022년 09월    28   107    71    71    32   203   검찰청4
57  2022년 10월    18   130    71    77    30   206   검찰청5
58  2022년 11월    12   140    82    73    32   187   검찰청2
59  2022년 12월    26   106    87    71    28   216   검찰청5

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      60 non-null     object
 1   폭력범죄    60 non-null     int64
 2   지능범죄    60 non-null     int64
 3   교통범죄    60 non-null     int64
 4   절도범죄    60 non-null     int64
 5   경제범죄    60 non-null     int64
 6   정치범죄    60 non-null     int64
 7   주요검찰청명  60 non-null     object
dtypes: int64(6), object(2)
memory usage: 3.9+ KB

In [74]:
df['총범죄건수'] = df.iloc[:,1:-1].sum(axis=1)
df

           날짜  폭력범죄  지능범죄  교통범죄  절도범죄  경제범죄  정치범죄 주요검찰청명  총범죄건수
0   2018년 01월    28   127    90    73    33   202   검찰청1    553
1   2018년 02월    16   137    72    80    30   180   검찰청5    515
2   2018년 03월    29   140    70    79    34   211   검찰청5    563
3   2018년 04월    10   140    90    65    31   184   검찰청1    520
4   2018년 05월    11   138    70    75    35   190   검찰청1    519
5   2018년 06월    30   128    78    74    34   216   검찰청5    560
6   2018년 07월    21   128    84    69    31   181   검찰청1    514
7   2018년 08월    26   120    86    76    33   188   검찰청5    529
8   2018년 09월    11   117    86    65    33   192   검찰청5    504
9   2018년 10월    12   117    86    67    28   200   검찰청5    510
10  2018년 11월    22   103    83    72    33   196   검찰청1    509
11  2018년 12월    28   124    83    61    27   209   검찰청2    532
12  2019년 01월    22   102    86    62    28   212   검찰청1    512
13  2019년 02월    26   138    80    61    31   183   검찰청3    519
14  2019년 03월    14   129    76    60    29   202   검찰청5    510
15  2019년 04월    26   142    83    71    33   182   검찰청1    537
16  2019년 05월    28   131    80    72    28   212   검찰청1    551
17  2019년 06월    22   104    84    72    34   201   검찰청2    517
18  2019년 07월    14   134    84    72    32   182   검찰청2    518
19  2019년 08월    27   101    71    67    31   198   검찰청1    495
20  2019년 09월    21   108    87    70    33   187   검찰청1    506
21  2019년 10월    21   114    89    61    32   212   검찰청3    529
22  2019년 11월    22   134    79    64    35   198   검찰청4    532
23  2019년 12월    21   142    77    62    35   183   검찰청3    520
24  2020년 01월    23   140    83    60    26   219   검찰청2    551
25  2020년 02월    11   111    73    60    31   211   검찰청1    497
26  2020년 03월    17   125    87    76    25   220   검찰청5    550
27  2020년 04월    10   112    78    78    28   185   검찰청3    491
28  2020년 05월    20   122    76    74    30   192   검찰청1    514
29  2020년 06월    24   139    87    77    29   192   검찰청3    548
30  2020년 07월    19   107    79    80    30   193   검찰청3    508
31  2020년 08월    27   124    81    62    29   187   검찰청5    510
32  2020년 09월    25   108    76    66    28   182   검찰청1    485
33  2020년 10월    25   134    71    75    33   189   검찰청5    527
34  2020년 11월    26   122    72    62    31   180   검찰청3    493
35  2020년 12월    22   104    87    80    31   181   검찰청5    505
36  2021년 01월    28   102    90    73    33   212   검찰청3    538
37  2021년 02월    16   173    72    80    50   150   검찰청2    541
38  2021년 03월    39   120    70    69    34   231   검찰청1    563
39  2021년 04월    26   122    83    71    33   192   검찰청4    527
40  2021년 05월    28   111    80    72    28   182   검찰청2    501
41  2021년 06월   122    94    84    92    34   211   검찰청2    637
42  2021년 07월    19   117    79    70    30   151   검찰청3    466
43  2021년 08월    27   131    81    62    29   189   검찰청5    519
44  2021년 09월    25   113    76    66    38   172   검찰청1    490
45  2021년 10월    20   115    80    77    33   138   검찰청3    463
46  2021년 11월    25   149    90    67    33   191   검찰청2    555
47  2021년 12월    21   116    87    72    38   206   검찰청4    540
48  2022년 01월    16   104    82    60    25   206   검찰청5    493
49  2022년 02월    19   145    88    60    30   204   검찰청1    546
50  2022년 03월    17   144    84    76    34   197   검찰청5    552
51  2022년 04월    14   150    85    75    31   181   검찰청5    536
52  2022년 05월    22   119    73    74    34   200   검찰청1    522
53  2022년 06월    12   131    78    65    30   201   검찰청3    517
54  2022년 07월    12   116    79    65    31   202   검찰청4    505
55  2022년 08월    25   129    77    69    33   185   검찰청2    518
56  2022년 09월    28   107    71    71    32   203   검찰청4    512
57  2022년 10월    18   130    71    77    30   206   검찰청5    532
58  2022년 11월    12   140    82    73    32   187   검찰청2    526
59  2022년 12월    26   106    87    71    28   216   검찰청5    534

In [75]:
df['연도'] = df['날짜'].str[:4]
df

           날짜  폭력범죄  지능범죄  교통범죄  절도범죄  경제범죄  정치범죄 주요검찰청명  총범죄건수    연도
0   2018년 01월    28   127    90    73    33   202   검찰청1    553  2018
1   2018년 02월    16   137    72    80    30   180   검찰청5    515  2018
2   2018년 03월    29   140    70    79    34   211   검찰청5    563  2018
3   2018년 04월    10   140    90    65    31   184   검찰청1    520  2018
4   2018년 05월    11   138    70    75    35   190   검찰청1    519  2018
5   2018년 06월    30   128    78    74    34   216   검찰청5    560  2018
6   2018년 07월    21   128    84    69    31   181   검찰청1    514  2018
7   2018년 08월    26   120    86    76    33   188   검찰청5    529  2018
8   2018년 09월    11   117    86    65    33   192   검찰청5    504  2018
9   2018년 10월    12   117    86    67    28   200   검찰청5    510  2018
10  2018년 11월    22   103    83    72    33   196   검찰청1    509  2018
11  2018년 12월    28   124    83    61    27   209   검찰청2    532  2018
12  2019년 01월    22   102    86    62    28   212   검찰청1    512  2019
13  2019년 02월    26   138    80    61    31   183   검찰청3    519  2019
14  2019년 03월    14   129    76    60    29   202   검찰청5    510  2019
15  2019년 04월    26   142    83    71    33   182   검찰청1    537  2019
16  2019년 05월    28   131    80    72    28   212   검찰청1    551  2019
17  2019년 06월    22   104    84    72    34   201   검찰청2    517  2019
18  2019년 07월    14   134    84    72    32   182   검찰청2    518  2019
19  2019년 08월    27   101    71    67    31   198   검찰청1    495  2019
20  2019년 09월    21   108    87    70    33   187   검찰청1    506  2019
21  2019년 10월    21   114    89    61    32   212   검찰청3    529  2019
22  2019년 11월    22   134    79    64    35   198   검찰청4    532  2019
23  2019년 12월    21   142    77    62    35   183   검찰청3    520  2019
24  2020년 01월    23   140    83    60    26   219   검찰청2    551  2020
25  2020년 02월    11   111    73    60    31   211   검찰청1    497  2020
26  2020년 03월    17   125    87    76    25   220   검찰청5    550  2020
27  2020년 04월    10   112    78    78    28   185   검찰청3    491  2020
28  2020년 05월    20   122    76    74    30   192   검찰청1    514  2020
29  2020년 06월    24   139    87    77    29   192   검찰청3    548  2020
30  2020년 07월    19   107    79    80    30   193   검찰청3    508  2020
31  2020년 08월    27   124    81    62    29   187   검찰청5    510  2020
32  2020년 09월    25   108    76    66    28   182   검찰청1    485  2020
33  2020년 10월    25   134    71    75    33   189   검찰청5    527  2020
34  2020년 11월    26   122    72    62    31   180   검찰청3    493  2020
35  2020년 12월    22   104    87    80    31   181   검찰청5    505  2020
36  2021년 01월    28   102    90    73    33   212   검찰청3    538  2021
37  2021년 02월    16   173    72    80    50   150   검찰청2    541  2021
38  2021년 03월    39   120    70    69    34   231   검찰청1    563  2021
39  2021년 04월    26   122    83    71    33   192   검찰청4    527  2021
40  2021년 05월    28   111    80    72    28   182   검찰청2    501  2021
41  2021년 06월   122    94    84    92    34   211   검찰청2    637  2021
42  2021년 07월    19   117    79    70    30   151   검찰청3    466  2021
43  2021년 08월    27   131    81    62    29   189   검찰청5    519  2021
44  2021년 09월    25   113    76    66    38   172   검찰청1    490  2021
45  2021년 10월    20   115    80    77    33   138   검찰청3    463  2021
46  2021년 11월    25   149    90    67    33   191   검찰청2    555  2021
47  2021년 12월    21   116    87    72    38   206   검찰청4    540  2021
48  2022년 01월    16   104    82    60    25   206   검찰청5    493  2022
49  2022년 02월    19   145    88    60    30   204   검찰청1    546  2022
50  2022년 03월    17   144    84    76    34   197   검찰청5    552  2022
51  2022년 04월    14   150    85    75    31   181   검찰청5    536  2022
52  2022년 05월    22   119    73    74    34   200   검찰청1    522  2022
53  2022년 06월    12   131    78    65    30   201   검찰청3    517  2022
54  2022년 07월    12   116    79    65    31   202   검찰청4    505  2022
55  2022년 08월    25   129    77    69    33   185   검찰청2    518  2022
56  2022년 09월    28   107    71    71    32   203   검찰청4    512  2022
57  2022년 10월    18   130    71    77    30   206   검찰청5    532  2022
58  2022년 11월    12   140    82    73    32   187   검찰청2    526  2022
59  2022년 12월    26   106    87    71    28   216   검찰청5    534  2022

In [76]:
df['월'] = df['날짜'].str[6:10]
df

           날짜  폭력범죄  지능범죄  교통범죄  절도범죄  경제범죄  정치범죄 주요검찰청명  총범죄건수    연도    월
0   2018년 01월    28   127    90    73    33   202   검찰청1    553  2018  01월
1   2018년 02월    16   137    72    80    30   180   검찰청5    515  2018  02월
2   2018년 03월    29   140    70    79    34   211   검찰청5    563  2018  03월
3   2018년 04월    10   140    90    65    31   184   검찰청1    520  2018  04월
4   2018년 05월    11   138    70    75    35   190   검찰청1    519  2018  05월
5   2018년 06월    30   128    78    74    34   216   검찰청5    560  2018  06월
6   2018년 07월    21   128    84    69    31   181   검찰청1    514  2018  07월
7   2018년 08월    26   120    86    76    33   188   검찰청5    529  2018  08월
8   2018년 09월    11   117    86    65    33   192   검찰청5    504  2018  09월
9   2018년 10월    12   117    86    67    28   200   검찰청5    510  2018  10월
10  2018년 11월    22   103    83    72    33   196   검찰청1    509  2018  11월
11  2018년 12월    28   124    83    61    27   209   검찰청2    532  2018  12월
12  2019년 01월    22   102    86    62    28   212   검찰청1    512  2019  01월
13  2019년 02월    26   138    80    61    31   183   검찰청3    519  2019  02월
14  2019년 03월    14   129    76    60    29   202   검찰청5    510  2019  03월
15  2019년 04월    26   142    83    71    33   182   검찰청1    537  2019  04월
16  2019년 05월    28   131    80    72    28   212   검찰청1    551  2019  05월
17  2019년 06월    22   104    84    72    34   201   검찰청2    517  2019  06월
18  2019년 07월    14   134    84    72    32   182   검찰청2    518  2019  07월
19  2019년 08월    27   101    71    67    31   198   검찰청1    495  2019  08월
20  2019년 09월    21   108    87    70    33   187   검찰청1    506  2019  09월
21  2019년 10월    21   114    89    61    32   212   검찰청3    529  2019  10월
22  2019년 11월    22   134    79    64    35   198   검찰청4    532  2019  11월
23  2019년 12월    21   142    77    62    35   183   검찰청3    520  2019  12월
24  2020년 01월    23   140    83    60    26   219   검찰청2    551  2020  01월
25  2020년 02월    11   111    73    60    31   211   검찰청1    497  2020  02월
26  2020년 03월    17   125    87    76    25   220   검찰청5    550  2020  03월
27  2020년 04월    10   112    78    78    28   185   검찰청3    491  2020  04월
28  2020년 05월    20   122    76    74    30   192   검찰청1    514  2020  05월
29  2020년 06월    24   139    87    77    29   192   검찰청3    548  2020  06월
30  2020년 07월    19   107    79    80    30   193   검찰청3    508  2020  07월
31  2020년 08월    27   124    81    62    29   187   검찰청5    510  2020  08월
32  2020년 09월    25   108    76    66    28   182   검찰청1    485  2020  09월
33  2020년 10월    25   134    71    75    33   189   검찰청5    527  2020  10월
34  2020년 11월    26   122    72    62    31   180   검찰청3    493  2020  11월
35  2020년 12월    22   104    87    80    31   181   검찰청5    505  2020  12월
36  2021년 01월    28   102    90    73    33   212   검찰청3    538  2021  01월
37  2021년 02월    16   173    72    80    50   150   검찰청2    541  2021  02월
38  2021년 03월    39   120    70    69    34   231   검찰청1    563  2021  03월
39  2021년 04월    26   122    83    71    33   192   검찰청4    527  2021  04월
40  2021년 05월    28   111    80    72    28   182   검찰청2    501  2021  05월
41  2021년 06월   122    94    84    92    34   211   검찰청2    637  2021  06월
42  2021년 07월    19   117    79    70    30   151   검찰청3    466  2021  07월
43  2021년 08월    27   131    81    62    29   189   검찰청5    519  2021  08월
44  2021년 09월    25   113    76    66    38   172   검찰청1    490  2021  09월
45  2021년 10월    20   115    80    77    33   138   검찰청3    463  2021  10월
46  2021년 11월    25   149    90    67    33   191   검찰청2    555  2021  11월
47  2021년 12월    21   116    87    72    38   206   검찰청4    540  2021  12월
48  2022년 01월    16   104    82    60    25   206   검찰청5    493  2022  01월
49  2022년 02월    19   145    88    60    30   204   검찰청1    546  2022  02월
50  2022년 03월    17   144    84    76    34   197   검찰청5    552  2022  03월
51  2022년 04월    14   150    85    75    31   181   검찰청5    536  2022  04월
52  2022년 05월    22   119    73    74    34   200   검찰청1    522  2022  05월
53  2022년 06월    12   131    78    65    30   201   검찰청3    517  2022  06월
54  2022년 07월    12   116    79    65    31   202   검찰청4    505  2022  07월
55  2022년 08월    25   129    77    69    33   185   검찰청2    518  2022  08월
56  2022년 09월    28   107    71    71    32   203   검찰청4    512  2022  09월
57  2022년 10월    18   130    71    77    30   206   검찰청5    532  2022  10월
58  2022년 11월    12   140    82    73    32   187   검찰청2    526  2022  11월
59  2022년 12월    26   106    87    71    28   216   검찰청5    534  2022  12월

In [88]:
a = df.groupby('연도')['총범죄건수'].mean()
print(a)
print(round(max(a)))
#max_crime = max(df.groupby(['연도','월'])['총범죄건수'].mean())
#max_crime

연도
2018    527.333333
2019    520.500000
2020    514.916667
2021    528.333333
2022    524.416667
Name: 총범죄건수, dtype: float64
528

## 2유형

In [89]:
train_df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_2_train.csv')
train_df

     일평균수면시간  일평균학습시간  일평균스마트폰사용시간      키     몸무게  체격   기초대사량 거주지역    구분
0       7.35     7.74          4.8   Tall  52.050   L  1499.4   동구  고등학생
1       7.05     8.10          1.2   Tall  51.300   M  1624.4   서구   중학생
2       7.35     7.74          3.0   Tall  51.285   L  1499.4   동구  고등학생
3       8.58     6.66          4.8  Short  25.545  XS  1249.5   서구  초등학생
4       7.05     8.10          4.8   Tall  54.150   M  1624.4   서구   대학생
..       ...      ...          ...    ...     ...  ..     ...  ...   ...
525    10.11     5.58          4.8  Short  25.185  XS  1874.3   동구  초등학생
526     8.27     6.84          1.2   Tall  51.165   M  2124.2   동구  고등학생
527     7.35     7.74          1.2   Tall  40.995   L  1499.4   동구   중학생
528    10.11     5.58          0.0  Short  18.330  XS  1874.3   동구  유치원생
529     6.44     8.82          3.0   Tall  44.535   S  1499.4   동구  고등학생

[530 rows x 9 columns]

In [90]:
test_df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_2_test.csv')
test_df

     일평균수면시간  일평균학습시간  일평균스마트폰사용시간      키     몸무게  체격   기초대사량 거주지역
0       7.97     7.11          1.2   Tall  51.375   L  1749.3   북구
1       9.80     5.76          1.2  Short  28.710  XS  1749.3   북구
2       7.66     7.38          1.2   Tall  36.915   L  1624.4   남구
3       9.50     5.94          3.0  Short  24.045  XS  1624.4   동구
4       6.44     8.82          3.0   Tall  45.180   S  1499.4   서구
..       ...      ...          ...    ...     ...  ..     ...  ...
225     9.80     5.76          3.0  Short  30.195  XS  1749.3   북구
226     8.58     6.66          4.8  Short  25.875  XS  1249.5   동구
227     8.27     6.84          1.2   Tall  50.460   M  2124.2   남구
228     7.66     7.38          4.8   Tall  48.645   L  1624.4   북구
229     9.80     5.76          4.8  Short  33.375  XS  1749.3   남구

[230 rows x 8 columns]